MagicVilla_Web/Models/APIRequest.cs
using static MagicVilla_Utilities.DS;

namespace MagicVilla_Web.Models
{
    public class APIRequest
    {
        public APIType APIType { get; set; } = APIType.GET;

        public string Url { get; set; }

        public object Data { get; set; }
    }
}

MagicVilla_Web/Models/APIResponse.cs
using System.Net;

namespace MagicVilla_Web.Models
{
    public class APIResponse
    {
        public HttpStatusCode statusCode { get; set; }
        public bool IsSuccessful { get; set; } = true;
        public List<string> ErrorMenssages { get; set; }
        public object Result { get; set; }
    }
}

MagicVilla_Web/Models/DTO/VillaCreateDto.cs
using System.ComponentModel.DataAnnotations;

namespace MagicVilla_Web.Models.DTO
{
    public class VillaCreateDto
    {
        [Required]
        [MaxLength(50)]
        public string Name { get; set; }
        public string Description { get; set; }
        [Required]
        public double Rate { get; set; }
        public int Occupants { get; set; }
        public int SquareMeters { get; set; }
        public string ImagenUrl { get; set; }
        public string Services { get; set; }
    }
}

MagicVilla_Web/Models/DTO/VillaDto.cs
using System.ComponentModel.DataAnnotations;

namespace MagicVilla_Web.Models.DTO
{
    public class VillaDto
    {
        public int Id { get; set; }
        [Required]
        [MaxLength(50)]
        public string Name { get; set; }
        public string Description { get; set; }
        [Required]
        public double Rate { get; set; }
        public int Occupants { get; set; }
        public int SquareMeters { get; set; }
        public string ImagenUrl { get; set; }
        public string Services { get; set; }
    }
}

MagicVilla_Web/Models/DTO/VillaNumberCreateDto.cs
using System.ComponentModel.DataAnnotations;

namespace MagicVilla_Web.Models.DTO
{
    public class VillaNumberCreateDto
    {
        [Required]
        public int VillaNum { get; set; }

        [Required]
        public int VillaId { get; set; }

        public string EspecialDetail { get; set; }
    }
}

MagicVilla_Web/Models/DTO/VillaNumberDto.cs
using System.ComponentModel.DataAnnotations;

namespace MagicVilla_Web.Models.DTO
{
    public class VillaNumberDto
    {
        [Required]
        public int VillaNum { get; set; }

        [Required]
        public int VillaId { get; set; }

        public string EspecialDetail { get; set; }
    }
}

MagicVilla_Web/Models/DTO/VillaNumberUpdateDto.cs
using System.ComponentModel.DataAnnotations;

namespace MagicVilla_Web.Models.DTO
{
    public class VillaNumberUpdateDto
    {
        [Required]
        public int VillaNum { get; set; }

        [Required]
        public int VillaId { get; set; }

        public string EspecialDetail { get; set; }
    }
}

MagicVilla_Web/Models/DTO/VillaUpdateDto.cs
using System.ComponentModel.DataAnnotations;

namespace MagicVilla_Web.Models.DTO
{
    public class VillaUpdateDto
    {
        [Required]
        public int Id { get; set; }
        [Required]
        [MaxLength(50)]
        public string Name { get; set; }
        public string Description { get; set; }
        [Required]
        public double Rate { get; set; }
        [Required]
        public int Occupants { get; set; }
        [Required]
        public int SquareMeters { get; set; }
        [Required]
        public string ImagenUrl { get; set; }
        public string Services { get; set; }
    }
}

MagicVilla_Web/Models/ErrorViewModel.cs
namespace MagicVilla_Web.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MagicVilla_Web/Controllers/HomeController.cs
using MagicVilla_Web.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace MagicVilla_Web.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MagicVilla_Web/Controllers/VillaController.cs
using AutoMapper;
using MagicVilla_Web.Models;
using MagicVilla_Web.Models.DTO;
using MagicVilla_Web.Services.IServices;
using Microsoft.AspNetCore.Mvc;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Newtonsoft.Json;
using System.Runtime.InteropServices;

namespace MagicVilla_Web.Controllers
{
    public class VillaController : Controller
    {
        private readonly IVillaService _villaService;
        private readonly IMapper _mapper;
        public VillaController(IVillaService villaService, IMapper mapper)
        {
            _villaService = villaService;
            _mapper = mapper;
        }

        public async Task<IActionResult> IndexVilla()
        {
            List<VillaDto> villaList = new();

            var response = await _villaService.GetAll<APIResponse>();

            if (response != null && response.IsSuccessful)
            {
                villaList = JsonConvert.DeserializeObject<List<VillaDto>>(Convert.ToString(response.Result));
            }

            return View(villaList);
        }

        //GET
        public async Task<IActionResult> CreateVilla()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateVilla(VillaCreateDto model)
        {
            if (ModelState.IsValid)
            {
                var response = await _villaService.Create<APIResponse>(model);

                if (response != null && response.IsSuccessful)
                {
                    return RedirectToAction("IndexVilla");
                }
            }
            return View(model);
        }

        public async Task<IActionResult> UpdateVilla (int villaId)
        {
            var response = await _villaService.Get<APIResponse>(villaId);

            if (response != null && response.IsSuccessful)
            {
                VillaDto model = JsonConvert.DeserializeObject<VillaDto>(Convert.ToString(response.Result));
                return View (_mapper.Map<VillaUpdateDto>(model));
            }
            return NotFound();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> UpdateVilla (VillaUpdateDto model)
        {
            if (ModelState.IsValid)
            {
                var response = await _villaService.Update<APIResponse>(model);
                
                if(response != null && response.IsSuccessful)
                {
                    return RedirectToAction(nameof(IndexVilla));
                }
            }
            return View(model);
        }
        
    }
}

MagicVilla_Web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

MagicVilla_Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MagicVilla_Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MagicVilla_Web.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MagicVilla_Web</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Villa" asp-action="IndexVilla">Villa</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - MagicVilla_Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

MagicVilla_Web/Views/Villa/CreateVilla.cshtml
@model MagicVilla_Web.Models.DTO.VillaCreateDto
@{
    ViewData["Title"] = "CreateVilla";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<form method="post" asp-action="CreateVilla">
    <div class="container border p-3">
        
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        
        <div class="row">
            <h2 class="text-info">Create new villa</h2>
        </div>

        <div class="row mt-2">
            <div class="col-md-6">
                <label class="form-label">Name Villa</label>
                <input asp-for="Name" class="form-control"/>
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
        </div>

        <div class="row mt-2">
            <div class="col-md-6">
                <label class="form-label">Rate</label>
                <input asp-for="Rate" class="form-control" />
                <span asp-validation-for="Rate" class="text-danger"></span>
            </div>
        </div>

        <div class="row mt-2">
            <div class="col-md-6">
                <label class="form-label">Description</label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
        </div>

        <div class="row mt-2">
            <div class="col-md-6">
                <label class="form-label">Image</label>
                <input asp-for="ImagenUrl" class="form-control" />
                <span asp-validation-for="ImagenUrl" class="text-danger"></span>
            </div>
        </div>

        <div class="row mt-2">
            <div class="col-md-6">
                <label class="form-label">Occupants</label>
                <input asp-for="Occupants" class="form-control" />
                <span asp-validation-for="Occupants" class="text-danger"></span>
            </div>
        </div>

        <div class="row mt-2">
            <div class="col-md-6">
                <label class="form-label">Square Meters</label>
                <input asp-for="SquareMeters" class="form-control" />
                <span asp-validation-for="SquareMeters" class="text-danger"></span>
            </div>
        </div>

        <div class="row mt-2">
            <div class="col-md-6">
                <label class="form-label">Services</label>
                <textarea asp-for="Services" class="form-control" ></textarea>
                <span asp-validation-for="Services" class="text-danger"></span>
            </div>
        </div>

        <div class="d-grid gap-2 d-md-block mt-2">
            <button type="submit" class="btn btn-primary">Save</button>
            <a asp-controller="Villa" asp-action="IndexVilla" class="btn btn-success">Return</a>
        </div>

    </div>
</form>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

MagicVilla_Web/Views/Villa/IndexVilla.cshtml
@model IEnumerable<MagicVilla_Web.Models.DTO.VillaDto>
@{
    ViewData["Title"] = "IndexVilla";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container p-4 border">
    <div class="row pb-2">
        <div class="col">
            <h1 class="text-primary">List of Villas</h1>
        </div>
        <div class="col text-end pt-1">
            <a asp-controller="Villa" asp-action="CreateVilla" class="btn btn-outline-primary"><i class="bi bi-plus-square-fill"></i> Create new villa</a>
        </div>
    </div>
</div>

<table class="table">
    <thead>
        <tr>
            <th>Name</th>
            <th>Occupants</th>
            <th>Rate</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach(var item in Model)
        {
            <tr>
                <td>@item.Name</td>
                <td>@item.Occupants</td>
                <td>@item.Rate.ToString("c")</td>
                <td>
                    <a asp-controller="Villa" asp-action="UpdateVilla" asp-route-villaId="@item.Id" class="btn btn-success"><i class="bi bi-pencil-square"></i> </a>
                    <a asp-controller="Villa" asp-action="DeleteVilla" asp-route-villaId="@item.Id" class="btn btn-danger"><i class="bi bi-trash-fill"></i> </a>
                </td>
            </tr>
        }
    </tbody>
</table>

MagicVilla_Web/Views/Villa/UpdateVilla.cshtml
@model MagicVilla_Web.Models.DTO.VillaUpdateDto
@{
    ViewData["Title"] = "UpdateVilla";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<form method="post" asp-action="UpdateVilla">
    <div class="container border p-3">

        <div asp-validation-summary="ModelOnly" class="text-danger"></div>

        <input hidden asp-for="Id" />

        <div class="row">
            <h2 class="text-info">Update villa</h2>
        </div>

        <div class="row mt-2">
            <div class="col-md-6">
                <label class="form-label">Name Villa</label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
        </div>

        <div class="row mt-2">
            <div class="col-md-6">
                <label class="form-label">Rate</label>
                <input asp-for="Rate" class="form-control" />
                <span asp-validation-for="Rate" class="text-danger"></span>
            </div>
        </div>

        <div class="row mt-2">
            <div class="col-md-6">
                <label class="form-label">Description</label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
        </div>

        <div class="row mt-2">
            <div class="col-md-6">
                <label class="form-label">Image</label>
                <input asp-for="ImagenUrl" class="form-control" />
                <span asp-validation-for="ImagenUrl" class="text-danger"></span>
            </div>
        </div>

        <div class="row mt-2">
            <div class="col-md-6">
                <label class="form-label">Occupants</label>
                <input asp-for="Occupants" class="form-control" />
                <span asp-validation-for="Occupants" class="text-danger"></span>
            </div>
        </div>

        <div class="row mt-2">
            <div class="col-md-6">
                <label class="form-label">Square Meters</label>
                <input asp-for="SquareMeters" class="form-control" />
                <span asp-validation-for="SquareMeters" class="text-danger"></span>
            </div>
        </div>

        <div class="row mt-2">
            <div class="col-md-6">
                <label class="form-label">Services</label>
                <textarea asp-for="Services" class="form-control"></textarea>
                <span asp-validation-for="Services" class="text-danger"></span>
            </div>
        </div>

        <div class="d-grid gap-2 d-md-block mt-2">
            <button type="submit" class="btn btn-primary">Update</button>
            <a asp-controller="Villa" asp-action="IndexVilla" class="btn btn-success">Return</a>
        </div>

    </div>
</form>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}